/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cwq_jni_JNILib */

#ifndef _Included_com_cwq_jni_JNILib
#define _Included_com_cwq_jni_JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cwq_jni_JNILib
 * Method:    initAssetManager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_initAssetManager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_cwq_jni_JNILib
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_cwq_jni_JNILib
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_cwq_jni_JNILib
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_onDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_cwq_jni_JNILib
 * Method:    onTouch
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_onTouch
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_cwq_jni_JNILib
 * Method:    clickCut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_clickCut
  (JNIEnv *, jclass);

/*
 * Class:     com_cwq_jni_JNILib
 * Method:    clickReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cwq_jni_JNILib_clickReset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
